import langSwitcher from "./langSwitcher.svg";
import instagram from "./instagram.svg";
import facebook from "./facebook.svg";
import twitter from "./twitter.svg";
import linkedin from "./linkedin.svg";
import hero from "./hero.svg";
import heroItem from "./heroItem.svg";
import hospitality from "./hospitality.svg";
import healthcare from "./healthcare.svg";
import housekeeping from "./housekeeping.svg";
import retail from "./retail.svg";
import manufacturing from "./manufacturing.svg";
import greenFuture from "./greenFuture.svg";
import healtcareLaundry from "./healtcareLaundry.svg";
import tunnelWasher from "./tunnelWasher.svg";
import careers from "./careers.svg";
import builfFuture from "./builfFuture.svg";
import life from "./life.svg";
import colaborative from "./colaborative.svg";
import workLife from "./workLife.svg";
import growth from "./growth.svg";
import environment from "./environment.svg";

export { environment, growth, workLife, colaborative, life, builfFuture, careers, tunnelWasher, healtcareLaundry, greenFuture, langSwitcher, instagram, facebook, twitter, linkedin, hero, heroItem, hospitality, healthcare, housekeeping, retail, manufacturing };
