import langSwitcher from "./langSwitcher.svg";
import instagram from "./instagram.svg";
import facebook from "./facebook.svg";
import twitter from "./twitter.svg";
import linkedin from "./linkedin.svg";
import hero from "./hero.webp";
import heroItem from "./heroItem.webp";
import hospitality from "./hospitality.svg";
import healthcare from "./healthcare.svg";
import housekeeping from "./housekeeping.svg";
import retail from "./retail.svg";
import manufacturing from "./manufacturing.svg";
import greenFuture from "./greenFuture.webp";
import healtcareLaundry from "./healtcareLaundry.png";
import tunnelWasher from "./tunnelWasher.webp";
import careers from "./careers.webp";
import builfFuture from "./builfFuture.webp";
import life from "./life.webp";
import colaborative from "./colaborative.svg";
import workLife from "./workLife.svg";
import growth from "./growth.svg";
import environment from "./environment.svg";

export { environment, growth, workLife, colaborative, life, builfFuture, careers, tunnelWasher, healtcareLaundry, greenFuture, langSwitcher, instagram, facebook, twitter, linkedin, hero, heroItem, hospitality, healthcare, housekeeping, retail, manufacturing };
